/**
 * Writes reports/data_report.md: when the automated figures were refreshed, which
 * topics each country has sources for, and which fields are still empty. The
 * "not sourced yet" column doubles as the to-do list for the next manual refresh.
 *
 * Usage: npm run report
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import * as yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const countriesDir = path.join(__dirname, '../data/countries');
const metaPath = path.join(__dirname, '../data/meta.yaml');
const reportsDir = path.join(__dirname, '../reports');

// Manually researched topics a complete profile should cite (see docs/DATA_SOURCES.md).
const TOPICS = ['pay', 'deductions', 'visa', 'tuition', 'living_costs', 'phd_system'];
// phd_system = typical duration and funders (not sourced yet).

function emptyFields(obj, prefix = '') {
  if (obj === null || obj === undefined || obj === '') return [prefix];
  if (Array.isArray(obj)) return obj.length === 0 ? [prefix] : obj.flatMap((v, i) => emptyFields(v, `${prefix}[${i}]`));
  if (typeof obj === 'object') return Object.entries(obj).flatMap(([k, v]) => emptyFields(v, prefix ? `${prefix}.${k}` : k));
  return [];
}

const meta = fs.existsSync(metaPath) ? yaml.load(fs.readFileSync(metaPath, 'utf8')) : null;
const profiles = fs.readdirSync(countriesDir)
  .filter(f => f.endsWith('.yaml'))
  .map(f => yaml.load(fs.readFileSync(path.join(countriesDir, f), 'utf8')))
  .sort((a, b) => a.name.localeCompare(b.name));

let md = '# Data report\n\n';
md += 'Generated by `npm run report`. See [docs/DATA_SOURCES.md](../docs/DATA_SOURCES.md) for how each figure is produced.\n\n';

md += '## Automated figures\n\n';
if (meta) {
  md += `Last refreshed with \`npm run data:refresh\` on **${meta.refreshed}**.\n\n| Figure | Source | Period |\n|---|---|---|\n`;
  for (const [key, s] of Object.entries(meta.automated_sources)) {
    md += `| ${key.replace(/_/g, ' ')} | [${s.source}](${s.url}) | ${s.year ?? s.period} |\n`;
  }
} else {
  md += '_data/meta.yaml is missing: run `npm run data:refresh`._\n';
}

md += '\n## Source coverage (manual research)\n\n';
md += '| Country | Sources | Oldest access date | Not sourced yet |\n|---|---|---|---|\n';
const todo = {};
for (const p of profiles) {
  const sources = p.sources || [];
  const topics = new Set(sources.map(s => s.topic));
  // Taxed salaries get their deductions from OECD automatically.
  if (p.stipend.is_taxable) topics.add('deductions');
  if (!p.stipend.is_taxable && p.stipend.deductions_percent === 0) topics.add('deductions');
  const missing = TOPICS.filter(t => !topics.has(t));
  missing.forEach(t => (todo[t] = (todo[t] || 0) + 1));
  const oldest = sources.map(s => s.accessed).sort()[0] || 'n/a';
  md += `| ${p.name} | ${sources.length} | ${oldest} | ${missing.join(', ') || 'none'} |\n`;
}
md += `\nStill unsourced across the dataset: ${Object.entries(todo).map(([t, n]) => `**${t}** (${n} countries)`).join(', ') || 'nothing'}.\n`;

md += '\n## Empty fields\n\n';
const empties = profiles.map(p => [p, emptyFields(p)]).filter(([, e]) => e.length > 0);
md += empties.length === 0
  ? 'No empty fields.\n'
  : empties.map(([p, e]) => `- **${p.name}**: ${e.map(f => `\`${f}\``).join(', ')}`).join('\n') + '\n';

fs.mkdirSync(reportsDir, { recursive: true });
fs.writeFileSync(path.join(reportsDir, 'data_report.md'), md, 'utf8');
console.log(`Report written to reports/data_report.md`);
