// Generated by scripts/build.js from data/countries/*.yaml (see lib/country-model.js).
import countriesData from '../../public/data/countries.json';
import metaData from '../../public/data/meta.json';

export interface Portal {
  title: string;
  url: string;
}

export interface Source {
  topic: 'pay' | 'deductions' | 'visa' | 'tuition' | 'phd_system' | 'living_costs' | 'funding';
  title: string;
  url: string;
  accessed: string; // YYYY-MM-DD
  note?: string;
}

export interface AutomatedSource {
  source: string;
  url: string;
  year?: number | string;
  period?: string;
}

export interface DataMeta {
  refreshed: string | null;
  automated_sources: Partial<Record<'price_level_index' | 'life_satisfaction' | 'climate' | 'pay_deductions' | 'exchange_rates', AutomatedSource>>;
}

export interface PayStep {
  label: string;
  note: string | null;
  grossMonthly: number; // EUR, annual extras spread over 12 months
  netMonthly: number; // EUR, estimate
  published: string; // e.g. "EUR 3,204 / month"
}

export interface Country {
  id: string;
  name: string;
  code: string;
  flag: string;
  region: string;
  capital: string;
  durationYears: number;
  duration: string;
  status: 'Employed' | 'Student' | 'Fellowship';
  grossSalary: number; // EUR per month
  netIncome: number; // EUR per month, rough estimate
  isTaxable: boolean;
  deductionsPercent: number; // income tax + employee social contributions, % of gross
  payBasis: string | null; // what the pay figure is, as published
  payScale: PayStep[]; // pay over the PhD / by contract; first entry = headline
  netIncomeMin: number; // EUR per month, lowest step
  netIncomeMax: number; // EUR per month, highest step
  tuitionFeesEU: number; // EUR per year
  tuitionFeesNonEU: number; // EUR per year
  costOfLiving: number; // EUR per month, midpoint of the range
  costOfLivingLow: number; // EUR per month, cheaper university city
  costOfLivingHigh: number; // EUR per month, most expensive university city
  costBasis: string | null; // what the range is, as published
  priceIndex: number; // EU average = 100
  priceLevel: 'Very low' | 'Low' | 'Average' | 'High' | 'Very high';
  fundingSources: string[];
  postStudyVisaMonths: number;
  euFreeMovement: boolean; // false for the UK since Brexit
  happinessIndex: number | null; // 0 to 10 life-satisfaction score
  climate: { summerC: number; winterC: number };
  portals: Portal[];
  sources: Source[];
  overview: string;
  pros: string[];
  cons: string[];
  warnings: string[];
}

export const countries = countriesData as Country[];
export const meta = metaData as DataMeta;
